export const API_ENDPOINTS = {
  auth: {
    signIn: '/auth/sign-in',
    signUp: '/auth/sign-up',
    verifySignupCode: '/auth/sign-up/verify-code',
    resendSignupCode: '/auth/sign-up/resend-code',
    forgotPassword: '/auth/password/forgot',
    verifyResetCode: '/auth/password/verify-code',
    resetPassword: '/auth/password/reset',
  },
  cases: {
    list: '/api/cases',
    create: '/api/cases',
    get: (caseId: string) => `/api/cases/${caseId}`,
    update: (caseId: string) => `/api/cases/${caseId}`,
    updateStatus: (caseId: string) => `/api/cases/${caseId}/status`,
    delete: (caseId: string) => `/api/cases/${caseId}`,
    listDrafts: '/api/cases/drafts',
    createDraft: '/api/cases/drafts',
    updateDraft: (caseId: string) => `/api/cases/drafts/${caseId}`,
    deleteDraft: (caseId: string) => `/api/cases/drafts/${caseId}`,
    markResultViewed: (caseId: string) => `/api/cases/${caseId}/result-viewed`,
  },
  signatures: {
    uploadReference: (caseId: string) => `/api/cases/${caseId}/signatures/reference`,
    uploadSuspect: (caseId: string) => `/api/cases/${caseId}/signatures/suspect`,
    getReference: (caseId: string, index: number) => `/api/cases/${caseId}/signatures/reference/${index}`,
    getSuspect: (caseId: string) => `/api/cases/${caseId}/signatures/suspect`,
    getAll: (caseId: string) => `/api/cases/${caseId}/signatures`,
    deleteReference: (caseId: string, index: number) => `/api/cases/${caseId}/signatures/reference/${index}`,
    deleteSuspect: (caseId: string) => `/api/cases/${caseId}/signatures/suspect`,
  },
  analysis: {
    start: (caseId: string) => `/api/cases/${caseId}/analysis`,
    getStatus: (caseId: string) => `/api/cases/${caseId}/analysis/status`,
    getResults: (caseId: string) => `/api/cases/${caseId}/analysis/results`,
    updateResults: (caseId: string) => `/api/cases/${caseId}/analysis/results`,
  },
} as const;
